version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports: 
      - "5432:5432"
    networks:
      - etl_network

  scheduler:
    image: apache/airflow
    command: scheduler
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - webserver
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - etl_network
    links:
      - 'postgres:postgres_database'

  webserver:
    image: apache/airflow
    entrypoint: ./scripts/entrypoint.sh
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    networks:
      - etl_network
    links:
      - 'postgres:postgres_database'

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - etl_network
    restart: unless-stopped
    
networks:
  etl_network:
    external: true