version: "3.0"
services:
  nifi:
    image: apache/nifi:1.11.3
    container_name: nifi
    ports:
      - 9300:8080
    networks:
      - etl_network
    volumes:
      - ./nifi_files:/opt/nifi/nifi-current/nifi_files
      - ./nifi_config:/opt/nifi/nifi-current/nifi_config
      - ./scripts:/opt/airflow/scripts

networks:
  etl_network:
    external: true